language: node_js
node_js:
  - 16  # Use a more recent Node.js version, such as 16
services:
  - docker

before_install:
  - docker build -t reactapp -f Dockerfile .
  
script:
  - docker run reactapp npm run test -- --coverage




