name: youtube-stats Actions CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install react-scripts
      run: npm install react-scripts
    - name: Add node_modules to PATH
      run: echo "export PATH=$PATH:$HOME/node_modules" >> ~/.bashrc
    - run: npm run build --if-present
    - name: Build and push Docker images
    - uses: docker/build-push-action@v4.1.1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          push: true
          tags: user/app:latest
            
