name: youtube-stats Actions CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install react-scripts
      run: npm install react-scripts
    - name: Add node_modules to PATH
      run: echo "export PATH=$PATH:$HOME/node_modules" >> ~/.bashrc
    - run: npm run build --if-present
